# Generated by Django 2.0.3 on 2018-03-22 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timeframe', '0003_auto_20180322_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='components',
        ),
        migrations.AddField(
            model_name='component',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Timeframe.Task'),
        ),
    ]
