# Generated by Django 2.0.3 on 2018-03-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeframe', '0004_auto_20180322_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
