# Generated by Django 2.0.3 on 2018-03-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeframe', '0005_auto_20180322_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
