# Generated by Django 2.0.3 on 2018-03-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeframe', '0007_auto_20180322_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
