# Generated by Django 2.0.3 on 2018-03-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timeframe', '0009_auto_20180322_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('-completed', '-created')},
        ),
    ]
